name: VarDecomp-APSIM
channels:
  - conda-forge
dependencies:
  - sqlite3
  - numpy as np
  - matplotlib.pyplot as plt
  - matplotlib.patches as mpatches
  - matplotlib.ticker as ticker
  - pandas as pd
  - seaborn as sns
